In [192]:
#DATA PROCESSING
#load the dataset
import pandas as pd

In [193]:
df = pd.read_csv("Car Dataset Processed.csv")

In [194]:
df.head()

,Unnamed: 0,car_name,registration_year,insurance_validity,fuel_type,seats,kms_driven,ownsership,transmission,manufacturing_year,mileage(kmpl),engine(cc),max_power(bhp),torque(Nm),price(in lakhs)
0,0,2017 Mercedes-Benz S-Class S400,Jul-17,Comprehensive,Petrol,5,56000,First Owner,Automatic,2017,7.81,2996.0,2996.0,333.0,63.75
1,1,2020 Nissan Magnite Turbo CVT XV Premium Opt BSVI,Jan-21,Comprehensive,Petrol,5,30615,First Owner,Automatic,2020,17.40,999.0,999.0,9863.0,8.99
2,2,2018 BMW X1 sDrive 20d xLine,Sep-18,Comprehensive,Diesel,5,24000,First Owner,Automatic,2018,20.68,1995.0,1995.0,188.0,23.75
3,3,2019 Kia Seltos GTX Plus,Dec-19,Comprehensive,Petrol,5,18378,First Owner,Manual,2019,16.50,1353.0,1353.0,13808.0,13.56
4,4,2019 Skoda Superb LK 1.8 TSI AT,Aug-19,Comprehensive,Petrol,5,44900,First Owner,Automatic,2019,14.67,1798.0,1798.0,17746.0,24.00

In [195]:
#to convert text data of columns to numbers
df["insurance_validity"].value_counts()

insurance_validity
Comprehensive            1081
Third Party insurance     289
Zero Dep                   64
Third Party                63
Not Available               2
Name: count, dtype: int64

In [196]:
mapping = {'Comprehensive':5,'Third Party insurance':1, 'Zero Dep':2,
                            'Not Available':3,'Third Party':1
          }

df["insurance_validity"]= df['insurance_validity'].map(mapping)

In [197]:
df["insurance_validity"].value_counts()

insurance_validity
5    1081
1     352
2      64
3       2
Name: count, dtype: int64

In [198]:
#now for fuel_type
df["fuel_type"].value_counts()

fuel_type
Petrol    997
Diesel    480
CNG        22
Name: count, dtype: int64

In [199]:
mapping1 = {
            'Petrol':0,
            'Diesel':1,
            'CNG':2
        }
df["fuel_type"]=df["fuel_type"].map(mapping1)

In [200]:
df["fuel_type"].value_counts()

fuel_type
0    997
1    480
2     22
Name: count, dtype: int64

In [201]:
#now for transmission type
df["transmission"].value_counts()

transmission
Manual       832
Automatic    667
Name: count, dtype: int64

In [202]:
mapping2 = {
            "Manual":5,
            "Automatic":1,
            }
df["transmission"]= df["transmission"].map(mapping2)

In [203]:
df["transmission"].value_counts()

transmission
5    832
1    667
Name: count, dtype: int64

In [204]:
#for ownership column
df["ownsership"].value_counts()

ownsership
First Owner     1236
Second Owner     240
Third Owner       21
Fifth Owner        2
Name: count, dtype: int64

In [205]:
mapping3={
            "First Owner":1,
            "Second Owner":2,
            "Third Owner":3,
            "Fifth Owner":5,
}
df["ownsership"]= df["ownsership"].map(mapping3)

In [206]:
df["ownsership"].value_counts()

ownsership
1    1236
2     240
3      21
5       2
Name: count, dtype: int64

In [207]:
#work on registration year
#make another column wherein there is only the years
df['registration_year'] = df['registration_year'].str.split('-').str[1]

In [208]:
df.head()

,Unnamed: 0,car_name,registration_year,insurance_validity,fuel_type,seats,kms_driven,ownsership,transmission,manufacturing_year,mileage(kmpl),engine(cc),max_power(bhp),torque(Nm),price(in lakhs)
0,0,2017 Mercedes-Benz S-Class S400,17,5,0,5,56000,1,1,2017,7.81,2996.0,2996.0,333.0,63.75
1,1,2020 Nissan Magnite Turbo CVT XV Premium Opt BSVI,21,5,0,5,30615,1,1,2020,17.40,999.0,999.0,9863.0,8.99
2,2,2018 BMW X1 sDrive 20d xLine,18,5,1,5,24000,1,1,2018,20.68,1995.0,1995.0,188.0,23.75
3,3,2019 Kia Seltos GTX Plus,19,5,0,5,18378,1,5,2019,16.50,1353.0,1353.0,13808.0,13.56
4,4,2019 Skoda Superb LK 1.8 TSI AT,19,5,0,5,44900,1,1,2019,14.67,1798.0,1798.0,17746.0,24.00

In [209]:
#model development
#insurance_validity,fuel_type,ownsership,kms_driven, transmission
#based on the baove columns we are gonna machine learning model
#as a datascientist these many columns shoule be less we used to use more

In [210]:
#Phase 1:input features
#x:insuarance_validity 2d object;all about numeric data
#y:price,

#types of objects:dictonaries
#this is a regression problem

X = df[["insurance_validity", "fuel_type", "kms_driven", "ownsership", "transmission"]]
Y = df["price(in lakhs)"]

In [211]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR

In [212]:
#define models
models= {'LinReg':LinearRegression(),
        'KNN-3':KNeighborsRegressor(n_neighbors=3),
        'SVM-Poly':SVR (kernel='poly')
     }
#trainin and evaluation
for name,model in models.items():
        model.fit(X,Y)      
        score = model.score(X,Y)
        print(name, score)

LinReg 0.018923228248963087
KNN-3 0.5927588998410543
SVM-Poly -0.002159339138024796

In [214]:
final_model = models['KNN-3']

In [217]:
insurance_validity = input('Insurance Validity: ')
fuel_type = input('Fuel Type: ')
kms_driven = int(input('KMs Driven: '))
ownership = input('ownership:')
transmission = input('Transmission type:')
insurance_validity = mapping[insurance_validity]
fuel_type =mapping1[fuel_type]
ownership =mapping3[ownership]
transmission = mapping2[transmission]
kms_driven = (int)(kms_driven)
test = [[insurance_validity,fuel_type,kms_driven,ownership,transmission]]
yp = final_model.predict(test)[0]
print(f'Predicted Car Price is {yp} Lakh')

Insurance Validity:  Comprehensive
Fuel Type:  Petrol
KMs Driven:  3000
ownership: First Owner
Transmission type: Manual

Predicted Car Price is 3.26 Lakh

C:\Users\Rashita\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(

In [218]:
#create a pickle file
import pickle
pickle.dump(final_model,open('final_model.pkl','wb')) #wb:write binary

#CREATE aa app.py file 

#commands required in anaconda prompt
#1 cd folderpath
#2 streamlit run app.py